### ISSUE TITLE
tabla productos

### ISSUE THREAD

**Issue by Valenry** [FC892/Actividades-Integradoras-de-Modulo#15]
Script de la creación de la tabla en la base ya existente.
Clases en Python.
Métodos de insert y select desde Python

**Comment by FC892** [comment]
-- table actividad3.productos
--------------------------------------------------------------

  CREATE TABLE IF NOT EXISTS `actividad3`.`productos` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_producto`))
  ENGINE = InnoDB;
