### ISSUE TITLE
tabla produccion diaria

### ISSUE THREAD

**Issue by Valenry** [FC892/Actividades-Integradoras-de-Modulo#16]
Script de la creación de la tabla en la base ya existente.
Clases en Python.
Métodos de insert y select desde Python

**Comment by Natru17** [comment]
-- Table `actividad3`.`produccion_diaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad3`.`produccion_diaria` (
  `id_produccion_diaria` INT NOT NULL AUTO_INCREMENT,
  `productos_id_producto` INT NOT NULL,
  `fecha` VARCHAR(30) NOT NULL,
  `cantidad_producida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_produccion_diaria`),
  CONSTRAINT `id_producto`
    FOREIGN KEY (`productos_id_producto`)
    REFERENCES `actividad3`.`productos` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_produccion_diaria_productos1_idx` ON `actividad3`.`produccion_diaria` (`productos_id_producto` ASC) VISIBLE;

**Comment by Natru17** [comment]
import mysql.connector

class Conexion:
    def __init__(self):
        self.conexion = mysql.connector.connect(
            user='root',
            password='Godoy1234',
            host='localhost',
            database='actividad3',
            port='3306'
        )

    def conectar(self):
        try:
            self.conexion.connect()
            print("Conexión exitosa a la base de datos")
        except mysql.connector.Error as error:
            print("Error al conectar a la base de datos:", error)

    def cerrar_conexion(self):
        self.conexion.close()
        print("Conexión cerrada")


class ProduccionDiaria:
    def __init__(self, conexion):
        self.conexion = conexion

    def insertar_produccion(self, productos_id_producto, fecha, cantidad_producida):
        cursor = self.conexion.cursor()
        try:
            query = "INSERT INTO produccion_diaria (productos_id_producto, fecha, cantidad_producida) VALUES (%s, %s, %s)"
            valores = (productos_id_producto, fecha, cantidad_producida)
            cursor.execute(query, valores)
            self.conexion.commit()
            print("Producción diaria insertada correctamente")
        except mysql.connector.Error as error:
            print("Error al insertar la producción diaria:", error)
        finally:
            cursor.close()

    def seleccionar_produccion(self):
        cursor = self.conexion.cursor()
        try:
            query = "SELECT * FROM produccion_diaria"
            cursor.execute(query)
            resultados = cursor.fetchall()
            print("Producción diaria:")
            for resultado in resultados:
                id_produccion, productos_id_producto, fecha, cantidad_producida = resultado
                print("ID producción:", id_produccion)
                print("ID producto:", productos_id_producto)
                print("Fecha:", fecha)
                print("Cantidad producida:", cantidad_producida)
                print("--------")
        except mysql.connector.Error as error:
            print("Error al seleccionar la producción diaria:", error)
        finally:
            cursor.close()


conexion = Conexion()
conexion.conectar()

produccion_manager = ProduccionDiaria(conexion.conexion)

produccion_manager.insertar_produccion(1, '2023-06-10', 100)

produccion_manager.seleccionar_produccion()

conexion.cerrar_conexion()
