### ISSUE TITLE
Crear Modelo en Lucys de DER- Big Bread SA

### ISSUE THREAD

**Issue by Valenry** [FC892/Actividades-Integradoras-de-Modulo#5]
[Big Bread SA - Calculadora de Insumos (4).pdf](https://github.com/FC892/Actividades-Integradoras-de-Modulo/files/11535871/Big.Bread.SA.-.Calculadora.de.Insumos.4.pdf)

**Comment by analiabelen** [comment]
Leido

**Comment by Valenry** [comment]
Modelo subido
